# Generated by Django 5.1.1 on 2024-11-05 09:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputDevice',
            fields=[
                ('input_device_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('device_name', models.CharField(max_length=24)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('device_protocol', models.CharField(choices=[('S7Rack', 'S7Rack'), ('S7Tsap', 'S7Tsap'), ('Modbus', 'Modbus')], default='S7Tsap', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='InputAddress',
            fields=[
                ('address_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('variable_name', models.CharField(max_length=24)),
                ('address', models.CharField(max_length=24)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iiot.inputdevice')),
            ],
        ),
    ]
