# Generated by Django 5.1.1 on 2024-11-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiot', '0002_mqttserver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputaddress',
            old_name='device_id',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='inputdevice',
            old_name='input_device_id',
            new_name='device_id',
        ),
    ]
