# Generated by Django 5.1.1 on 2024-11-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiot', '0003_rename_device_id_inputaddress_device_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InputAddress',
            new_name='InputAddresses',
        ),
        migrations.RenameModel(
            old_name='InputDevice',
            new_name='InputDevices',
        ),
        migrations.RenameModel(
            old_name='MqttServer',
            new_name='MqttServers',
        ),
    ]
