# Generated by Django 5.1.1 on 2024-11-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiot', '0004_rename_inputaddress_inputaddresses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputdevices',
            name='rack',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='inputdevices',
            name='port',
            field=models.IntegerField(default=1),
        ),
    ]
