# Generated by Django 5.1.1 on 2024-11-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiot', '0005_inputdevices_rack_alter_inputdevices_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputdevices',
            name='slot',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='inputdevices',
            name='port',
            field=models.IntegerField(),
        ),
    ]
