# Generated by Django 5.1.1 on 2024-11-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiot', '0006_inputdevices_slot_alter_inputdevices_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputaddresses',
            name='data',
            field=models.CharField(default='', max_length=24),
        ),
    ]
