# Generated by Django 5.1.1 on 2024-11-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiot', '0007_inputaddresses_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttservers',
            name='topic',
            field=models.CharField(default='iiot/data', max_length=24),
        ),
    ]
