# Generated by Django 5.1.1 on 2024-11-10 08:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiot', '0008_mqttservers_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluxDatabase',
            fields=[
                ('device_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('device_name', models.CharField(default='iiot_influx', max_length=24)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('user_name', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=24)),
            ],
        ),
    ]
