# Generated by Django 5.1.1 on 2024-11-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiot', '0009_influxdatabase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influxdatabase',
            name='device_name',
            field=models.CharField(max_length=24),
        ),
    ]
