# Generated by Django 5.1.1 on 2024-11-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiot', '0010_alter_influxdatabase_device_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influxdatabase',
            name='password',
        ),
        migrations.RemoveField(
            model_name='influxdatabase',
            name='user_name',
        ),
        migrations.AddField(
            model_name='influxdatabase',
            name='database',
            field=models.CharField(default=1, max_length=24),
            preserve_default=False,
        ),
    ]
