# Generated by Django 5.1.1 on 2024-11-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiot', '0011_remove_influxdatabase_password_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfluxDatabase',
            new_name='InfluxDatabases',
        ),
    ]
