# Generated by Django 5.1.1 on 2024-11-10 10:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiot', '0012_rename_influxdatabase_influxdatabases'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluxMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('measurement_name', models.CharField(max_length=24)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iiot.inputaddresses')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iiot.influxdatabases')),
            ],
        ),
    ]
