# Generated by Django 5.1.1 on 2024-11-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiot', '0013_influxmeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='influxdatabases',
            name='duration',
            field=models.CharField(default='4w', max_length=24),
        ),
    ]
